---
apiVersion: batch/v1
kind: Job
metadata:
  name: validation-hook-{{ .Values.SERVICE_NAME }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-200"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/name: {{ .Values.SERVICE_NAME }}
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
    app.kubernetes.io/part-of: {{ .Values.APPLICATION_NAME | default "dbaas" }}
spec:
  backoffLimit: 5
  template:
    metadata:
      name: validation-hook-{{ .Values.SERVICE_NAME }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: validation-hook-{{ .Values.SERVICE_NAME }}
        image: {{ .Values.DECLARATIVE_HOOK_IMAGE }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ .Values.SERVICE_NAME }}-env-variables
      restartPolicy: Never
{{- end }}