{{- $namespace := print .Values.NAMESPACE }}
{{- $defaultDatabaseName := regexReplaceAll "-" $namespace "_" }}
{{- $pgDbaasName := .Values.POSTGRES_DBAAS_DATABASE_NAME | default $defaultDatabaseName }}
{{- $pgDbaasUser := .Values.POSTGRES_DBAAS_USER | default "postgres" }}
{{- $pgDbaasPassword := .Values.POSTGRES_DBAAS_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE_NAME }}-env-variables
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-201"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
stringData:
  NAMESPACE: {{ .Values.NAMESPACE }}
  USE_POSTGRES_PORT_FORWARD: {{ .Values.USE_POSTGRES_PORT_FORWARD | default "false" | quote }}
  PORT_FORWARD_PID: ""
  CLOUD_PUBLIC_HOST: {{ .Values.CLOUD_PUBLIC_HOST | default "" |quote }}
  POSTGRES_HOST: {{ .Values.POSTGRES_HOST | default "pg-patroni.postgresql" | quote }}
  POSTGRES_PORT: {{ .Values.POSTGRES_PORT | default "5432" | quote }}
  POSTGRES_DBA_USER: {{ .Values.POSTGRES_DBA_USER | default "postgres" | quote }}
  POSTGRES_DBA_PASSWORD: {{ .Values.POSTGRES_DBA_PASSWORD | quote }}
  DBAAS_OWN_PG_DB_CREATED_MANUALLY: {{ .Values.DBAAS_OWN_PG_DB_CREATED_MANUALLY | default "false" | quote }}
  POSTGRES_DBAAS_DATABASE_NAME: {{ quote $pgDbaasName }}
  POSTGRES_DBAAS_USER: {{ quote $pgDbaasUser }}
  POSTGRES_DBAAS_PASSWORD: {{ quote $pgDbaasPassword }}
