---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}