{
 "title": "DBAAS Dashboard (Spring Boot 2 Services)",
 "description": "Shows statistics and health details of selected DBaaS instance on selected cloud: \\n - health status of each adapter and DBaaS aggregator \\n - load factor—number of requests to DBaaS \\n - number of data bases that are and are not registered in DBaaS. If DB wasn’t created by DBaaS but was created directly \\n - it can cause problems for backup and maintenance procedures, so it is important to keep tracking such cases \\n - JVM parameters for each DBaaS adapter and aggregator.",
 "tags": [
  "Java",
  "Prometheus",
  "DbaaS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(jvm_memory_used_bytes{}, container)"
   },
   {
    "name": "namespace",
    "label": "DBAAS Project",
    "query": "label_values(jvm_memory_used_bytes{container='$service_name',}, namespace)"
   },
   {
    "name": "adapter",
    "label": "DbaaS adapter",
    "query": "label_values(dbaas_adapter_health{namespace='$namespace', container='$service_name',}, type)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "jvm_heap_part",
    "label": "JVM Heap Parts",
    "query": "label_values(jvm_memory_used_bytes{namespace='$namespace', container='$service_name', area='heap',}, id)"
   },
   {
    "name": "jvm_nonheap_part",
    "label": "JVM Non Heap Parts",
    "query": "label_values(jvm_memory_used_bytes{namespace='$namespace', container='$service_name', area='nonheap',}, id)"
   },
   {
    "name": "jvm_buffers_type",
    "label": "JVM Byte Buffer Types",
    "query": "label_values(jvm_buffer_memory_used_bytes{namespace='$namespace', container='$service_name',}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "singlestat",
   "description": "(-1 = UNKNOWN, 0 = OK, 3 = WARN, 6 = PROBLEM, 10 = FATAL)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_running{exported_namespace=\"$namespace\", exported_pod!~\".*deploy\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(value) from \"ma.status\"  WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' and $timeFilter group by time($interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(uptime) from \"ma.pod_info\"  WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(jvm_threads_live_threads{namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"value\") from \"ma.jvm_threads_live_threads\"  WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\" = 'dbaas-aggregator'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(jvm_classes_loaded_classes{namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"value\") from \"ma.jvm_classes_loaded_classes\"  WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "usage",
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "usage",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE \"namespace\" ='$dbaas_namespace' AND \"name\" = 'dbaas-aggregator' AND $timeFilter GROUP BY time($interval), pod_name fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "limit",
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE \"namespace\" ='$dbaas_namespace' AND \"name\" = 'dbaas-aggregator' AND $timeFilter GROUP BY time($interval), pod_name fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "request",
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE \"namespace\" ='$dbaas_namespace' AND \"name\" = 'dbaas-aggregator' AND $timeFilter GROUP BY time($interval), pod_name fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commited Memory",
   "type": "graph",
   "description": "The amount of used memory (Stack value)",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Pod Limit",
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limits",
     "query": "SELECT mean(\"value\") FROM \"memory/limit\" WHERE namespace ='$dbaas_namespace' AND container_name= 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pod Usage",
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Request",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE namespace ='$dbaas_namespace' AND container_name= 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pod Usage",
     "expr": "avg(container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE namespace ='$dbaas_namespace' AND container_name= 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heap",
     "expr": "avg(sum(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "NonHeap",
     "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'heap' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap",
     "expr": "avg(sum(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heap",
     "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "description": "The open file descriptor count (average for current time interval)",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "expr": "avg(process_files_open_files{container=\"$service_name\", namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "open",
     "query": "SELECT mean(\"value\") FROM \"ma.process_files_open_files\" WHERE namespace ='$dbaas_namespace' AND service_name= 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Databases Number By Registration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "not registered databases",
     "expr": "avg(dbaas_registration_databases_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "not registered databases",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.ghost.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "registered databases",
     "expr": "avg(dbaas_registration_databases_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "registered databases",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.total.number\"  WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number Of Databases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "not registered",
     "expr": "avg(dbaas_registration_databases_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "not registered",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.ghost.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total registered",
     "expr": "avg(dbaas_registration_databases_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "total registered",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lost",
     "expr": "avg(dbaas_registration_databases_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "lost",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.lost.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Adapter health status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type: $tag_identifier",
     "expr": "avg(dbaas_adapter_health{container=\"$service_name\", namespace=\"$namespace\"}) by (type, identifier)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} : {{identifier}}",
     "query": "SELECT mean(\"value\") FROM \"ma.dbaas.adapter.health\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval), type, identifier fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Adapter Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests to adapter $adapter by operation",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "repeat": "adapter",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_operation: $tag_result",
       "expr": "avg(dbaas_adapter_database_operation_request_total{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"} - dbaas_adapter_database_operation_request_total{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"} offset $__interval) by (operation, result) OR on() vector(0) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}: {{result}}",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas_adapter_database_operation_request_total\" WHERE \"type\"='$adapter' AND $timeFilter GROUP BY time($__interval), operation, result fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Duration of operations by adapter $adapter",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "repeat": "adapter",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_operation",
       "expr": "avg(increase(dbaas_adapter_database_operation_seconds_sum{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"}[$inter])/increase(dbaas_adapter_database_operation_seconds_count{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"}[$inter]) OR on() vector(0)) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"ma.dbaas_adapter_database_operation_seconds_sum\" WHERE \"type\"='$adapter' AND $timeFilter GROUP BY time($__interval), operation fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of registered databases per adapter type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Postgresql",
       "expr": "avg(dbaas_registration_databases_postgresql_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Postgresql",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.postgresql.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Mongodb",
       "expr": "avg(dbaas_registration_databases_mongodb_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mongodb",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.mongodb.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Cassandra",
       "expr": "avg(dbaas_registration_databases_cassandra_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Cassandra",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.cassandra.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Elasticsearch",
       "expr": "avg(dbaas_registration_databases_elasticsearch_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Elasticsearch",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.elasticsearch.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Redis",
       "expr": "avg(dbaas_registration_databases_redis_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Redis",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.redis.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of not registered databases per adapter type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Postgresql",
       "expr": "avg(dbaas_registration_databases_postgresql_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Postgresql",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.postgresql.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Mongodb",
       "expr": "avg(dbaas_registration_databases_mongodb_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mongodb",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.mongodb.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Cassandra",
       "expr": "avg(dbaas_registration_databases_cassandra_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Cassandra",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.cassandra.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Elasticsearch",
       "expr": "avg(dbaas_registration_databases_elasticsearch_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Elasticsearch",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.elasticsearch.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Redis",
       "expr": "avg(dbaas_registration_databases_redis_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Redis",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.redis.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of lost databases per adapter type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Postgresql",
       "expr": "avg(dbaas_registration_databases_postgresql_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Postgresql",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.postgresql.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Mongodb",
       "expr": "avg(dbaas_registration_databases_mongodb_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mongodb",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.mongodb.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Cassandra",
       "expr": "avg(dbaas_registration_databases_cassandra_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Cassandra",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.cassandra.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Elasticsearch",
       "expr": "avg(dbaas_registration_databases_elasticsearch_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Elasticsearch",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.elasticsearch.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Redis",
       "expr": "avg(dbaas_registration_databases_redis_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Redis",
       "query": "SELECT mean(\"value\") FROM \"ma.dbaas.registration.databases.redis.total.number\" WHERE \"namespace\" ='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "repeat": "jvm_heap_part",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_max_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_committed_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_max_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_committed_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_max_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_committed_bytes\" WHERE namespace =~ /^$dbaas_namespace$/ AND service_name = 'dbaas-aggregator' AND area = 'heap' AND \"id\"='$jvm_heap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non Heap: $jvm_nonheap_part",
     "type": "graph",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "jvm_nonheap_part",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap' AND \"id\"='$jvm_nonheap_part'  AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_max_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap'  AND \"id\"='$jvm_nonheap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_committed_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap'  AND \"id\"='$jvm_nonheap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Non Heap: $jvm_nonheap_part",
     "type": "graph",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap' AND \"id\"='$jvm_nonheap_part'  AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_max_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap'  AND \"id\"='$jvm_nonheap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_memory_committed_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND area = 'nonheap'  AND \"id\"='$jvm_nonheap_part' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Byte buffers: $jvm_buffers_type",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "repeat": "jvm_buffers_type",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_buffer_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND \"id\"='$jvm_buffers_type' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "capacity",
       "expr": "avg(jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "capacity",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_buffer_total_capacity_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND \"id\"='$jvm_buffers_type'  AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Byte buffers: $jvm_buffers_type",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "avg(jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_buffer_memory_used_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND \"id\"='$jvm_buffers_type' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "capacity",
       "expr": "avg(jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "capacity",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_buffer_total_capacity_bytes\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND \"id\"='$jvm_buffers_type'  AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC: Pauses",
     "type": "graph",
     "description": "Time spent for minor and major GC per second",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "pauses/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_cause: $tag_action",
       "expr": "avg(rate(jvm_gc_pause_seconds_sum{container=\"$service_name\", namespace=\"$namespace\"}[$inter])) by (cause, action)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{cause}}: {{action}}",
       "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ma.jvm_gc_pause_seconds_sum\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval), cause, action fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC: Allocations",
     "type": "graph",
     "description": "Increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "pauses/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_cause: $tag_action",
       "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocations",
       "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"ma.jvm_gc_memory_allocated_bytes_total\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval), cause, action fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "current",
       "expr": "avg(jvm_threads_live_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "current",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_threads_live_threads\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "daemon",
       "expr": "avg(jvm_threads_daemon_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "daemon",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_threads_daemon_threads\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "peak",
       "expr": "avg(jvm_threads_peak_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "peak",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_threads_peak_threads\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads: State",
     "type": "graph",
     "description": "Shows information about Java threads",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "avg(jvm_threads_states_threads{container=\"$service_name\", namespace=\"$namespace\"}) by (state)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "query": "SELECT mean(\"value\") FROM \"ma.jvm_threads_states_threads\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval), state fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL JDBC Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active",
       "expr": "avg(jdbc_connections_active{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Active",
       "query": "SELECT max(\"value\") FROM \"ma.jdbc_connections_active\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max",
       "expr": "avg(jdbc_connections_max{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max",
       "query": "SELECT mean(\"value\") FROM \"ma.jdbc_connections_max\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hickari Pool: Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active",
       "expr": "avg(hikaricp_connections_active{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Active",
       "query": "SELECT mean(\"value\") FROM \"ma.hikaricp_connections_active\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Idle",
       "expr": "avg(hikaricp_connections_idle{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Idle",
       "query": "SELECT mean(\"value\") FROM \"ma.hikaricp_connections_idle\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max",
       "expr": "avg(hikaricp_connections_max{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max",
       "query": "SELECT mean(\"value\") FROM \"ma.hikaricp_connections_max\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Pending",
       "expr": "avg(hikaricp_connections_pending{container=\"$service_name\", namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pending",
       "query": "SELECT mean(\"value\") FROM \"ma.hikaricp_connections_pending\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hickari Pool: Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Usage",
       "expr": "avg(rate(hikaricp_connections_usage_seconds_sum{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Usage",
       "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"ma.hikaricp_connections_usage_seconds_sum\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Count",
       "expr": "avg(increase(hikaricp_connections_usage_seconds_count{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Count",
       "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"ma.hikaricp_connections_usage_seconds_count\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log events",
     "type": "graph",
     "description": "Logback logging event stream",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "event/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_level",
       "expr": "avg(rate(logback_events_total{container=\"$service_name\", namespace=\"$namespace\"}[$inter])) by (level)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{level}}",
       "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"ma.logback_events_total\" WHERE \"namespace\"='$dbaas_namespace' AND \"service_name\"='dbaas-aggregator' AND $timeFilter GROUP BY time($__interval), level fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 2xx Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"2..\"}[$inter])) by (uri)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "query": "SELECT  non_negative_derivative(mean(value), 1s) FROM \"ma.http_server_requests_seconds_count\" WHERE namespace ='$dbaas_namespace' AND service_name = 'dbaas-aggregator'  AND status =~ /^2.+/ AND $timeFilter GROUP BY time($__interval), uri fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Timings. Code 2xx",
     "type": "graph",
     "description": "Shows maximum time of requests execution to service endpoints",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "avg(increase(http_server_requests_seconds_max{container=\"$service_name\", namespace=\"$namespace\"}[$inter])) by (uri) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "query": "SELECT non_negative_derivative(mean(value)) from \"ma.http_server_requests_seconds_max\"  WHERE service_name='dbaas-aggregator' AND \"namespace\"='$dbaas_namespace' AND status=~/^2.+/  AND $timeFilter GROUP BY time($__interval), uri\n fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 4xx",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"4..\"}[$inter])) by (uri) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ma.http_server_requests_seconds_count\" WHERE namespace ='$dbaas_namespace' AND status=~/^4.+/ AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY uri, time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 5xx",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"5..\"}[$inter])) by (uri) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ma.http_server_requests_seconds_count\" WHERE namespace ='$dbaas_namespace' AND status=~/^5.+/ AND service_name = 'dbaas-aggregator' AND $timeFilter GROUP BY uri, time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}