name: Build on Commit

on:
  workflow_dispatch:

jobs:
  mvn:
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode package -Dgpg.skip=true -DskipTests=true"
      server-id: "github"
      upload-artifact: true
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  call-docker-publish:
    runs-on: ubuntu-latest
    name: Docker Publish
    needs: mvn
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - uses: rparf/qubership-workflow-hub/actions/docker-publish@main
        with:
          artifact-id: "artifact"
          download-artifact: true
          ref: ${{ github.event.ref }}
